/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { clientsClaim } from 'workbox-core';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst, StaleWhileRevalidate } from 'workbox-strategies';
import { ExpirationPlugin } from 'workbox-expiration';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare let self: ServiceWorkerGlobalScope;

// Extended notification options to include vibrate pattern and actions
interface ExtendedNotificationOptions extends NotificationOptions {
  vibrate?: number[];
  requireInteraction?: boolean;
  actions?: Array<{ action: string; title: string; icon?: string }>;
}

// Take control immediately
self.skipWaiting();
clientsClaim();

// Clean up old caches
cleanupOutdatedCaches();

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Cache Supabase API calls with NetworkFirst strategy
registerRoute(
  ({ url }) => url.hostname.includes('supabase.co'),
  new NetworkFirst({
    cacheName: 'supabase-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 50,
        maxAgeSeconds: 60 * 60 * 24, // 24 hours
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache Google Fonts with CacheFirst strategy
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' || url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 30,
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
      }),
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
    ],
  })
);

// Cache images with CacheFirst strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images-cache',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 60 * 60 * 24 * 30, // 30 days
      }),
    ],
  })
);

// Cache JS/CSS with StaleWhileRevalidate
registerRoute(
  ({ request }) => request.destination === 'script' || request.destination === 'style',
  new StaleWhileRevalidate({
    cacheName: 'static-resources',
  })
);

// ========================================
// Push Notification Handlers
// ========================================

// Event listener para push notifications
self.addEventListener('push', function(event) {
  console.log('Push notification received:', event);
  
  let notificationData: ExtendedNotificationOptions & { title?: string } = {
    title: 'Dr. Memo',
    body: 'Você tem uma notificação',
    icon: '/icon-192.png',
    badge: '/icon-192.png',
    vibrate: [200, 100, 200],
    data: {
      dateOfArrival: Date.now(),
      primaryKey: 1,
      clickAction: '/'
    }
  };

  if (event.data) {
    try {
      const data = event.data.json();
      notificationData = {
        ...notificationData,
        ...data
      };
    } catch (e) {
      console.error('Error parsing push data:', e);
    }
  }

  event.waitUntil(
    self.registration.showNotification(notificationData.title || 'Dr. Memo', notificationData)
  );
});

// Event listener para cliques na notificação
self.addEventListener('notificationclick', function(event) {
  console.log('Notification clicked:', event);
  
  event.notification.close();

  const data = event.notification.data || {};
  const clickAction = data.clickAction || '/';

  // Tratar ação "Marcar como tomado"
  if (event.action === 'mark_taken' && data.medicationId && data.userId) {
    console.log('📝 Marcando medicação como tomada:', data.medicationId);
    
    event.waitUntil(
      fetch('https://qxuiymmzjptpczodbvmm.supabase.co/functions/v1/mark-medication-taken', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          medication_id: data.medicationId,
          scheduled_time: data.scheduledTime,
          user_id: data.userId,
        }),
      })
      .then(response => {
        if (response.ok) {
          console.log('✅ Medicação marcada como tomada com sucesso');
          return self.registration.showNotification('Dr. Memo ✅', {
            body: 'Medicação registrada com sucesso!',
            icon: '/icon-192.png',
            badge: '/icon-192.png',
            tag: 'medication-success',
            requireInteraction: false,
          });
        } else {
          console.error('❌ Erro ao marcar medicação:', response.status);
          return self.registration.showNotification('Dr. Memo ❌', {
            body: 'Erro ao registrar medicação. Tente novamente.',
            icon: '/icon-192.png',
            badge: '/icon-192.png',
            tag: 'medication-error',
          });
        }
      })
      .catch(error => {
        console.error('❌ Erro na requisição:', error);
        return self.registration.showNotification('Dr. Memo ❌', {
          body: 'Erro de conexão. Verifique sua internet.',
          icon: '/icon-192.png',
          badge: '/icon-192.png',
          tag: 'medication-error',
        });
      })
    );
  } else if (event.action === 'snooze' && data.medicationId) {
    console.log('⏰ Adiando notificação:', data.medicationId);
    event.waitUntil(
      self.registration.showNotification('Dr. Memo ⏰', {
        body: 'Notificação adiada por 10 minutos',
        icon: '/icon-192.png',
        badge: '/icon-192.png',
        tag: 'medication-snoozed',
      })
    );
  }

  // Abrir ou focar no app
  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true })
      .then((clientList) => {
        for (const client of clientList) {
          if (client.url.includes(clickAction) && 'focus' in client) {
            return client.focus();
          }
        }
        if (self.clients.openWindow) {
          return self.clients.openWindow(clickAction);
        }
      })
  );
});

// Listener para mensagens do app (mostrar notificação sob demanda)
self.addEventListener('message', function(event) {
  if (event.data && event.data.type === 'SHOW_NOTIFICATION') {
    const { title, body, icon, badge } = event.data.payload;
    
    const options: ExtendedNotificationOptions = {
      body,
      icon: icon || '/icon-192.png',
      badge: badge || '/icon-192.png',
      vibrate: [200, 100, 200],
      tag: 'dr-memo-notification',
      requireInteraction: true,
      actions: [
        {
          action: 'open',
          title: 'Abrir App'
        },
        {
          action: 'dismiss',
          title: 'Dispensar'
        }
      ]
    };
    
    self.registration.showNotification(title, options as NotificationOptions);
  }
});
